[package]
name = "sheeet-funcs"
version = "0.1.1"
edition = "2024"
description = "Sheeet base functions crate."
license = "MIT"
repository = "https://github.com/tikinang/sheeet"
homepage = "https://sheeet.matejpavlicek.cz"

[dependencies]
wasm-bindgen = "0.2.100"

[features]
http = []